version: "3.9"
services:
  registry:
    build: .
    command: python -m database.clustering.metadata_service
    ports:
      - "9100:9100"

  node1:
    build: .
    environment:
      NODE_ID: node1
      GRPC_PORT: 50051
      API_PORT: 8001
      DATA_DIR: /data
      PEERS: node2:50052,node3:50053
      REGISTRY_HOST: registry
      REGISTRY_PORT: 9100
    ports:
      - "50051:50051"
      - "8001:8001"
    depends_on:
      - registry
    volumes:
      - node1-data:/data

  node2:
    build: .
    environment:
      NODE_ID: node2
      GRPC_PORT: 50052
      API_PORT: 8002
      DATA_DIR: /data
      PEERS: node1:50051,node3:50053
      REGISTRY_HOST: registry
      REGISTRY_PORT: 9100
    ports:
      - "50052:50052"
      - "8002:8002"
    depends_on:
      - registry
    volumes:
      - node2-data:/data

  node3:
    build: .
    environment:
      NODE_ID: node3
      GRPC_PORT: 50053
      API_PORT: 8003
      DATA_DIR: /data
      PEERS: node1:50051,node2:50052
      REGISTRY_HOST: registry
      REGISTRY_PORT: 9100
    ports:
      - "50053:50053"
      - "8003:8003"
    depends_on:
      - registry
    volumes:
      - node3-data:/data

volumes:
  node1-data:
  node2-data:
  node3-data:
